### ISSUE TITLE
Real Estate Pro logo

### ISSUE THREAD

**Issue by bhubbard** [imFORZA/re-pro#29]
Plugin Approved, I need assets for this project:
https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by vinnylabarbera** [comment]
Assets attached
[RE Pro Assets.zip](https://github.com/imFORZA/re-pro/files/562336/RE.Pro.Assets.zip)

**Comment by bhubbard** [comment]
For Reference, just uploading the old ones here.
[TMP-Logo:Banners.zip](https://github.com/imFORZA/re-pro/files/562348/TMP-Logo.Banners.zip)
