### ISSUE TITLE
HTTPS Check for Widgets

### ISSUE THREAD

**Issue by bhubbard** [imFORZA/re-pro#33]
Some widgets use iFrames and will not work on HTTPS sites, so we should add a check for these.

**Comment by matoledo** [comment]
Done for Zillow widgets.

Check for Homes.com widgets.

**Comment by matoledo** [comment]
Added https check for Homes.com widgets.

**Comment by bhubbard** [comment]
Lets close this out, just remember going forward to test any widgets with HTTPS.
