### ISSUE TITLE
WP_PLUGIN_URL breaking SSL sites (caused by mixed content errors)

### ISSUE THREAD

**Issue by SmartAlecTony** [imFORZA/re-pro#49]
Our site uses an SSL. The plugin seems to pull resources using http. I've looked around and found that `wp_iv_property_URLPATH` is defined by `WP_PLUGIN_URL` which doesn't take an SSL into account. I've patched that up with `plugins_url()` but we need a more solid fix in case the plugin is updated in the future, which it will be. Thanks. 

Correction: The culprit file is plugin.php (plugins/real_estate_pro/plugin.php) around line 238.

**Comment by matoledo** [comment]
Hi @SmartAlecTony, 
This plugin does not contain a templates folder. I think you may be referring to a different plugin from CodeCanyon with a similar name.

**Comment by SmartAlecTony** [comment]
Referring to: [https://wordpress.org/plugins/re-pro/]. That was an oversight on my part, the issue is in plugin.php at the plugin root

**Comment by bhubbard** [comment]
https://wordpress.org/support/topic/plugin-bug-3/

**Comment by bhubbard** [comment]
@SmartAlecTony Reviewing the information you provided it still appears you are referring to another plugin or theme.

Our plugin does not have a plugin.php file, and the folder for our plugin is `re-pro` not `real_estate_pro`. Maybe you have our plugin installed in addition to another Real Estate plugin or Theme? 

Can you provide some more info to the issue you are having? We have tested the plugin on sites using HTTPS without any issues. Is there a particular widget you are having issues with?

**Comment by SmartAlecTony** [comment]
You're right. It looks like the "View Details" link on the plugins page pulls up your plugin. I've found out that the problematic plugin isn't listed on WP, so yours is linked since they're similar (which caused the confusion on my part). Thanks for the quick response.

**Comment by bhubbard** [comment]
@SmartAlecTony Hey not a problem. Closing Issue.
