### ISSUE TITLE
PHP Warnings

### ISSUE THREAD

**Issue by bhubbard** [imFORZA/re-pro#51]
https://wordpress.org/support/topic/errors-and-more-errors/

As soon as I activated this plugin and the screen refreshed, I was filled with “failed to open stream: No such file or directory in…” error messages.

Warning: include(widgets/class-large-search-box.php): failed to open stream: No such file or directory in /home/xx/public_html/wp-content/plugins/re-pro/modules/zillow/zillow.php on line 20

Warning: include(widgets/class-large-search-box.php): failed to open stream: No such file or directory in /home/xx/public_html/wp-content/plugins/re-pro/modules/zillow/zillow.php on line 20

Warning: include(): Failed opening ‘widgets/class-large-search-box.php’ for inclusion (include_path=’.:/opt/php56/lib/php’) in /home/xx/public_html/wp-content/plugins/re-pro/modules/zillow/zillow.php on line 20

Warning: include(widgets/class-newest-homes-widget.php): failed to open stream: No such file or directory in /home/xx/public_html/wp-content/plugins/re-pro/modules/zillow/zillow.php on line 24

Warning: include(widgets/class-newest-homes-widget.php): failed to open stream: No such file or directory in /home/xx/public_html/wp-content/plugins/re-pro/modules/zillow/zillow.php on line 24

Warning: include(): Failed opening ‘widgets/class-newest-homes-widget.php’ for inclusion (include_path=’.:/opt/php56/lib/php’) in /home/xx/public_html/wp-content/plugins/re-pro/modules/zillow/zillow.php on line 24

Warning: include_once(streetadvisor/streetadvisor.php): failed to open stream: No such file or directory in /home/xx/public_html/wp-content/plugins/re-pro/modules/modules.php on line 16

Warning: include_once(): Failed opening ‘streetadvisor/streetadvisor.php’ for inclusion (include_path=’.:/opt/php56/lib/php’) in /home/xx/public_html/wp-content/plugins/re-pro/modules/modules.php on line 16

Warning: include_once(greatschools/greatschools.php): failed to open stream: No such file or directory in /home/xx/public_html/wp-content/plugins/re-pro/modules/modules.php on line 18

Warning: include_once(): Failed opening ‘greatschools/greatschools.php’ for inclusion (include_path=’.:/opt/php56/lib/php’) in /home/xx/public_html/wp-content/plugins/re-pro/modules/modules.php on line 18

They showed in the back-end, and front-end. Clicking the ‘settings’ button on the plugin page only worked as an anchor, and it would take me back to the top of the page.

Frustrating, and uninstalled.

**Comment by sfgarza** [comment]
I’ve attempted to reproduce the errors above, but am unable to do so without further information. I will be closing out this issue for the time being until more details are supplied. The bug with the settings link on the plugin page has been fixed and will be available on the next release
